name: fit_tracker
description: "App for recording workouts."
publish_to: "none"
version: 0.22.0

environment:
  sdk: ^3.6.0

dependencies:
  intl:
    sdk: flutter
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_advanced_calendar: ^1.4.3

  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  path_provider_foundation: ^2.4.1
  sqflite: ^2.4.1
  path: 1.9.1
  typed_data: 1.4.0

dependency_overrides:
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/database/TestDB.db
    - assets/icons/MuscleGroup/dark/
    - assets/icons/MuscleGroup/white/
flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"
